<?php

namespace Database\Seeders;

use App\Models\BriggsTrainingScenario;
use Illuminate\Database\Seeder;

class BriggsTrainingScenarioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $scenarios = [
            [
                'title' => 'The Price Objection',
                'slug' => 'the-price-objection',
                'description' => 'A mid-market buyer pushes back on pricing. Practice reframing value over cost and handling budget concerns with confidence.',
                'category' => 'objection_handling',
                'difficulty' => 'beginner',
                'industry' => 'Healthcare',
                'buyer_persona' => 'Sarah is a pragmatic operations leader who evaluates everything through an ROI lens. She is friendly but firm on budget. She needs clear justification for any spend above her initial expectations.',
                'buyer_name' => 'Sarah Chen',
                'buyer_title' => 'VP of Operations',
                'buyer_company' => 'MedTech Corp',
                'scenario_context' => 'You are on a follow-up call after sending a proposal. Sarah likes the product but says the price is 30% higher than expected. She has budget authority but needs to justify the spend to her CFO.',
                'objectives' => [
                    'Acknowledge the pricing concern without discounting immediately',
                    'Reframe the conversation around ROI and total cost of ownership',
                    'Identify the specific budget constraints',
                    'Propose creative solutions (phased rollout, pilot program)',
                ],
                'scoring_criteria' => [
                    ['criterion' => 'Empathy & Acknowledgment', 'weight' => 20, 'description' => 'Validates the buyer concern before countering'],
                    ['criterion' => 'Value Reframing', 'weight' => 25, 'description' => 'Shifts conversation from price to value and ROI'],
                    ['criterion' => 'Discovery Questions', 'weight' => 20, 'description' => 'Asks questions to understand budget constraints'],
                    ['criterion' => 'Creative Solutions', 'weight' => 20, 'description' => 'Offers flexible options without undermining price'],
                    ['criterion' => 'Next Steps', 'weight' => 15, 'description' => 'Closes with a clear path forward'],
                ],
                'common_objections' => [
                    'Your price is 30% higher than what we budgeted.',
                    'Our CFO needs hard ROI numbers before approving this.',
                    'Your competitor offered us a lower price for similar features.',
                    'Can you just give us a discount?',
                ],
                'sort_order' => 1,
            ],
            [
                'title' => 'The Cold Call Opener',
                'slug' => 'the-cold-call-opener',
                'description' => 'Practice opening a cold call to a mid-market SaaS company. Get past the first 30 seconds and earn the right to continue the conversation.',
                'category' => 'cold_call',
                'difficulty' => 'beginner',
                'industry' => 'SaaS',
                'buyer_persona' => 'David is a busy IT Director who gets 5-10 cold calls per day. He is polite but quick to end calls that do not immediately show relevance. He responds well to specificity and brevity.',
                'buyer_name' => 'David Rodriguez',
                'buyer_title' => 'Director of IT',
                'buyer_company' => 'CloudFirst Solutions',
                'scenario_context' => 'You are calling David cold. He answers the phone. You have 30 seconds to earn the right to continue the conversation. He does not know who you are or what you sell.',
                'objectives' => [
                    'Open with a pattern interrupt or permission-based opener',
                    'Demonstrate relevance within the first 15 seconds',
                    'Earn permission to continue the conversation',
                    'Transition to a discovery question',
                ],
                'scoring_criteria' => [
                    ['criterion' => 'Opening Hook', 'weight' => 30, 'description' => 'Captures attention in the first 10 seconds'],
                    ['criterion' => 'Relevance', 'weight' => 25, 'description' => 'Connects to a likely pain point or business challenge'],
                    ['criterion' => 'Brevity', 'weight' => 20, 'description' => 'Keeps the opener concise and focused'],
                    ['criterion' => 'Transition', 'weight' => 15, 'description' => 'Smoothly moves to a discovery question'],
                    ['criterion' => 'Tone & Confidence', 'weight' => 10, 'description' => 'Professional and confident without being pushy'],
                ],
                'common_objections' => [
                    'I am in a meeting, can you call back?',
                    'We are not interested.',
                    'Just send me an email.',
                    'How did you get my number?',
                ],
                'sort_order' => 2,
            ],
            [
                'title' => 'Discovery Call Deep Dive',
                'slug' => 'discovery-call-deep-dive',
                'description' => 'Run a discovery call to uncover pain points, understand priorities, and qualify the opportunity. Practice asking layered questions and active listening.',
                'category' => 'discovery_call',
                'difficulty' => 'intermediate',
                'industry' => 'SaaS',
                'buyer_persona' => 'Lisa is analytical and data-driven. She has a clear picture of what her team needs but wants to see if you understand her world before committing time. She respects reps who ask smart questions.',
                'buyer_name' => 'Lisa Park',
                'buyer_title' => 'Head of Revenue',
                'buyer_company' => 'GrowthMetrics Inc',
                'scenario_context' => 'Lisa agreed to a 30-minute discovery call after seeing your outreach. She is evaluating 2-3 vendors. This is your chance to differentiate through the quality of your questions and understanding of her challenges.',
                'objectives' => [
                    'Establish the current state and key pain points',
                    'Understand decision criteria and timeline',
                    'Identify all stakeholders in the buying process',
                    'Qualify budget and authority',
                    'Set clear next steps',
                ],
                'scoring_criteria' => [
                    ['criterion' => 'Question Quality', 'weight' => 25, 'description' => 'Asks layered, open-ended questions that uncover real needs'],
                    ['criterion' => 'Active Listening', 'weight' => 25, 'description' => 'Builds on answers rather than following a rigid script'],
                    ['criterion' => 'Qualification', 'weight' => 20, 'description' => 'Covers BANT or MEDDIC criteria naturally'],
                    ['criterion' => 'Rapport Building', 'weight' => 15, 'description' => 'Creates a consultative, peer-level dynamic'],
                    ['criterion' => 'Next Steps', 'weight' => 15, 'description' => 'Proposes specific, time-bound next steps'],
                ],
                'common_objections' => [
                    'Can you just show me a demo instead?',
                    'We are early in the process, just exploring options.',
                    'I am not the final decision maker.',
                    'What makes you different from [competitor]?',
                ],
                'sort_order' => 3,
            ],
            [
                'title' => 'The Competitor Comparison',
                'slug' => 'the-competitor-comparison',
                'description' => 'Your prospect is actively evaluating a direct competitor. Practice differentiating without bashing the competition and redirecting to your unique strengths.',
                'category' => 'objection_handling',
                'difficulty' => 'intermediate',
                'industry' => 'Technology',
                'buyer_persona' => 'James is a technical leader who does thorough vendor evaluations. He uses feature comparison spreadsheets and values transparency. He will challenge any unsupported claims.',
                'buyer_name' => 'James Foster',
                'buyer_title' => 'CTO',
                'buyer_company' => 'DataStream Analytics',
                'scenario_context' => 'James is in the final stages of evaluating your product against a well-known competitor. He has a feature comparison spreadsheet and wants to understand where you are stronger and where you are weaker.',
                'objectives' => [
                    'Acknowledge the competitor without disparaging them',
                    'Redirect to your unique differentiators',
                    'Ask what criteria matter most to their decision',
                    'Build a case around outcomes rather than features',
                ],
                'scoring_criteria' => [
                    ['criterion' => 'Professional Positioning', 'weight' => 25, 'description' => 'Discusses competitor respectfully while differentiating'],
                    ['criterion' => 'Value Differentiation', 'weight' => 25, 'description' => 'Highlights unique strengths tied to buyer needs'],
                    ['criterion' => 'Discovery Integration', 'weight' => 20, 'description' => 'Uses questions to understand what matters most'],
                    ['criterion' => 'Evidence & Proof', 'weight' => 15, 'description' => 'Supports claims with data, case studies, or examples'],
                    ['criterion' => 'Closing Momentum', 'weight' => 15, 'description' => 'Advances the deal toward a decision'],
                ],
                'common_objections' => [
                    '[Competitor] has feature X that you do not.',
                    'Their pricing is more transparent.',
                    'We have been using them for years already.',
                    'Can you match their pricing?',
                ],
                'sort_order' => 4,
            ],
            [
                'title' => 'Executive Pitch to C-Suite',
                'slug' => 'executive-pitch-to-c-suite',
                'description' => 'Deliver a 15-minute pitch to a CEO. Practice executive-level communication, strategic framing, and handling tough questions from a time-pressed leader.',
                'category' => 'pitch',
                'difficulty' => 'advanced',
                'industry' => 'Retail',
                'buyer_persona' => 'Margaret is a results-oriented CEO with limited patience for fluff. She thinks strategically and cares about competitive advantage, market share, and shareholder value. She will interrupt if you lose her attention.',
                'buyer_name' => 'Margaret Williams',
                'buyer_title' => 'CEO',
                'buyer_company' => 'RetailEdge Corp',
                'scenario_context' => 'You have a 15-minute slot with Margaret after her VP of Sales championed your solution internally. Margaret wants to understand the strategic value, not features. She has 3 questions she cares about: Why now? Why you? What is the risk?',
                'objectives' => [
                    'Open with a strategic insight, not a product pitch',
                    'Frame the problem in terms of business impact',
                    'Present your solution as a competitive advantage',
                    'Address risk and implementation concerns proactively',
                    'Ask for a specific commitment',
                ],
                'scoring_criteria' => [
                    ['criterion' => 'Strategic Framing', 'weight' => 25, 'description' => 'Leads with business impact, not product features'],
                    ['criterion' => 'Executive Presence', 'weight' => 20, 'description' => 'Communicates with confidence and brevity'],
                    ['criterion' => 'Insight Delivery', 'weight' => 20, 'description' => 'Provides a perspective the CEO has not considered'],
                    ['criterion' => 'Risk Mitigation', 'weight' => 20, 'description' => 'Addresses implementation risk proactively'],
                    ['criterion' => 'Ask & Close', 'weight' => 15, 'description' => 'Makes a clear, confident ask'],
                ],
                'common_objections' => [
                    'Why should I prioritize this over other initiatives?',
                    'What happens if this does not work?',
                    'Our team is already stretched thin.',
                    'How quickly will we see results?',
                ],
                'sort_order' => 5,
            ],
            [
                'title' => 'Closing the Deal',
                'slug' => 'closing-the-deal',
                'description' => 'The prospect has seen the demo and received the proposal. Practice moving from evaluation to commitment and handling last-minute hesitation.',
                'category' => 'closing',
                'difficulty' => 'intermediate',
                'industry' => 'Technology',
                'buyer_persona' => 'Tom is enthusiastic about the product but cautious about making the wrong decision. He has authority to sign but tends to overthink. He responds well to confidence and clear next steps.',
                'buyer_name' => 'Tom Baker',
                'buyer_title' => 'VP of Sales',
                'buyer_company' => 'InnovateTech',
                'scenario_context' => 'Tom saw the demo last week and received the proposal. He said he likes everything but has not signed. This call is your opportunity to understand any remaining concerns and close.',
                'objectives' => [
                    'Confirm interest and address any remaining concerns',
                    'Create urgency without being pushy',
                    'Summarize the value agreed upon',
                    'Ask for the commitment directly',
                ],
                'scoring_criteria' => [
                    ['criterion' => 'Concern Resolution', 'weight' => 25, 'description' => 'Identifies and addresses remaining hesitations'],
                    ['criterion' => 'Value Reinforcement', 'weight' => 20, 'description' => 'Reconnects to the agreed-upon value and outcomes'],
                    ['criterion' => 'Urgency Creation', 'weight' => 20, 'description' => 'Creates genuine urgency without high pressure'],
                    ['criterion' => 'Direct Ask', 'weight' => 20, 'description' => 'Confidently asks for the close'],
                    ['criterion' => 'Handling Stalls', 'weight' => 15, 'description' => 'Manages think-it-over or check-with-team stalls'],
                ],
                'common_objections' => [
                    'I just need a few more days to think about it.',
                    'I need to run this by my team one more time.',
                    'Can we start with a smaller commitment?',
                    'What if it does not work out?',
                ],
                'sort_order' => 6,
            ],
            [
                'title' => 'The Follow-Up After Ghosting',
                'slug' => 'the-follow-up-after-ghosting',
                'description' => 'Your prospect went silent after a great demo. Practice re-engaging without being desperate and reigniting interest.',
                'category' => 'follow_up',
                'difficulty' => 'beginner',
                'industry' => 'Marketing',
                'buyer_persona' => 'Amanda is a busy marketing manager juggling multiple priorities. She genuinely liked the demo but got pulled into a major campaign launch. She feels guilty about not responding but needs a compelling reason to re-engage.',
                'buyer_name' => 'Amanda Ross',
                'buyer_title' => 'Marketing Manager',
                'buyer_company' => 'BrightPath Media',
                'scenario_context' => 'Amanda had a great demo 2 weeks ago but has not responded to your last 2 emails. You are calling to re-engage. She might pick up or you might get voicemail.',
                'objectives' => [
                    'Re-engage without guilt-tripping or being aggressive',
                    'Reference specific value from the previous conversation',
                    'Provide a new insight or reason to continue',
                    'Establish a concrete next step',
                ],
                'scoring_criteria' => [
                    ['criterion' => 'Tone & Approach', 'weight' => 25, 'description' => 'Professional and helpful without desperation'],
                    ['criterion' => 'Contextual Reference', 'weight' => 25, 'description' => 'References specific details from the previous conversation'],
                    ['criterion' => 'New Value Add', 'weight' => 20, 'description' => 'Brings something new to the conversation'],
                    ['criterion' => 'Persistence Balance', 'weight' => 15, 'description' => 'Persistent but respectful of their time'],
                    ['criterion' => 'Next Steps', 'weight' => 15, 'description' => 'Proposes a clear, easy next step'],
                ],
                'common_objections' => [
                    'Sorry, I have been slammed with work.',
                    'We decided to put this on hold for now.',
                    'I am not sure the timing is right anymore.',
                    'Can you just send me an email with the details?',
                ],
                'sort_order' => 7,
            ],
            [
                'title' => 'Budget Objection - Enterprise',
                'slug' => 'budget-objection-enterprise',
                'description' => 'The CFO pushes back on total cost of ownership for an enterprise deal. Practice navigating complex financial objections with a finance-focused buyer.',
                'category' => 'objection_handling',
                'difficulty' => 'advanced',
                'industry' => 'Logistics',
                'buyer_persona' => 'Robert is a numbers-driven CFO who evaluates every purchase through financial models. He is skeptical of vendor claims and demands detailed ROI calculations. He respects data and detests vague promises.',
                'buyer_name' => 'Robert Kim',
                'buyer_title' => 'CFO',
                'buyer_company' => 'Global Logistics Corp',
                'scenario_context' => 'Robert joins the final evaluation call to scrutinize the financials. The VP of Sales loves your product, but Robert has concerns about TCO, implementation costs, and payback period. He has a spreadsheet with pointed questions.',
                'objectives' => [
                    'Present a clear ROI framework with specific numbers',
                    'Address TCO concerns with transparent cost breakdown',
                    'Differentiate between cost and investment',
                    'Provide comparable customer financial outcomes',
                    'Gain financial approval to proceed',
                ],
                'scoring_criteria' => [
                    ['criterion' => 'Financial Literacy', 'weight' => 25, 'description' => 'Speaks the language of finance (ROI, TCO, payback period)'],
                    ['criterion' => 'Data-Driven Responses', 'weight' => 25, 'description' => 'Supports claims with specific numbers and benchmarks'],
                    ['criterion' => 'Transparency', 'weight' => 20, 'description' => 'Honest about costs without hiding anything'],
                    ['criterion' => 'Customer Proof', 'weight' => 15, 'description' => 'References similar customer financial outcomes'],
                    ['criterion' => 'Closing for Approval', 'weight' => 15, 'description' => 'Asks for financial sign-off or clear next step'],
                ],
                'common_objections' => [
                    'What is the total cost of ownership over 3 years?',
                    'Your implementation costs are higher than expected.',
                    'How do you justify a 12-month payback period?',
                    'Show me customer data that proves this ROI.',
                ],
                'sort_order' => 8,
            ],
            [
                'title' => 'Multi-Stakeholder Negotiation',
                'slug' => 'multi-stakeholder-negotiation',
                'description' => 'Handle a procurement team that wants discounts, extended payment terms, and additional scope. Practice protecting your deal value while building consensus.',
                'category' => 'negotiation',
                'difficulty' => 'advanced',
                'industry' => 'Manufacturing',
                'buyer_persona' => 'Patricia is a seasoned procurement leader whose job is to extract maximum value from every vendor. She is professional but tough. She uses tactics like anchoring, silence, and competing offers to negotiate aggressively.',
                'buyer_name' => 'Patricia Hayes',
                'buyer_title' => 'Head of Procurement',
                'buyer_company' => 'Atlas Industries',
                'scenario_context' => 'Your champion (the VP of Engineering) has approved the solution, but Patricia from procurement now leads the negotiation. She wants a 25% discount, 90-day payment terms, and free onboarding. You need to protect deal value while closing.',
                'objectives' => [
                    'Hold your pricing without damaging the relationship',
                    'Trade concessions strategically (give to get)',
                    'Identify what the buyer truly values most',
                    'Reach an agreement that works for both sides',
                    'Maintain your champion relationship through the process',
                ],
                'scoring_criteria' => [
                    ['criterion' => 'Price Protection', 'weight' => 25, 'description' => 'Holds firm on core pricing with confidence'],
                    ['criterion' => 'Strategic Trading', 'weight' => 25, 'description' => 'Trades concessions rather than giving them away'],
                    ['criterion' => 'Relationship Management', 'weight' => 20, 'description' => 'Maintains positive rapport through tough negotiation'],
                    ['criterion' => 'Creative Solutions', 'weight' => 15, 'description' => 'Offers alternatives that create mutual value'],
                    ['criterion' => 'Deal Closing', 'weight' => 15, 'description' => 'Reaches a firm agreement with clear terms'],
                ],
                'common_objections' => [
                    'We need at least 25% off to get this approved.',
                    'Your competitor is willing to do this for less.',
                    'We need 90-day payment terms, not 30.',
                    'Throw in free onboarding and we have a deal.',
                ],
                'sort_order' => 9,
            ],
            [
                'title' => 'SaaS Discovery - Pain Points',
                'slug' => 'saas-discovery-pain-points',
                'description' => 'Your first discovery call with a SaaS operations manager. Practice uncovering pain points and connecting them to your solution value.',
                'category' => 'discovery_call',
                'difficulty' => 'beginner',
                'industry' => 'SaaS',
                'buyer_persona' => 'Eric is an operations manager at a growing startup. He is overwhelmed with manual processes and knows he needs a better solution but is not sure what to prioritize. He is open and honest but short on time.',
                'buyer_name' => 'Eric Nguyen',
                'buyer_title' => 'Operations Manager',
                'buyer_company' => 'StartupHub',
                'scenario_context' => 'Eric responded to your outreach and booked a 20-minute call. He mentioned "operational inefficiencies" but did not elaborate. You need to uncover the specific pain points and determine if there is a fit.',
                'objectives' => [
                    'Build initial rapport and set the agenda',
                    'Uncover 2-3 specific pain points through questioning',
                    'Understand the impact of these pain points on the business',
                    'Determine if there is a fit for your solution',
                    'Schedule a follow-up or demo if qualified',
                ],
                'scoring_criteria' => [
                    ['criterion' => 'Agenda Setting', 'weight' => 15, 'description' => 'Sets a clear agenda and timeframe upfront'],
                    ['criterion' => 'Pain Discovery', 'weight' => 30, 'description' => 'Uncovers specific, quantifiable pain points'],
                    ['criterion' => 'Impact Understanding', 'weight' => 20, 'description' => 'Explores the business impact of each pain point'],
                    ['criterion' => 'Fit Assessment', 'weight' => 20, 'description' => 'Honestly assesses whether there is a solution fit'],
                    ['criterion' => 'Next Steps', 'weight' => 15, 'description' => 'Proposes a logical next step based on the conversation'],
                ],
                'common_objections' => [
                    'I only have about 15 minutes today.',
                    'We have tried other tools before and they did not work.',
                    'I am not sure what our budget is for this.',
                    'Can you just send me some information?',
                ],
                'sort_order' => 10,
            ],
        ];

        foreach ($scenarios as $scenario) {
            BriggsTrainingScenario::query()->updateOrCreate(
                ['slug' => $scenario['slug']],
                $scenario
            );
        }
    }
}
